export interface Driver {
  slug: string;
  number: number;
  firstName: string;
  lastName: string;
  nationality: string;
  countryCode: string;
  dateOfBirth: string;
  team: string;
  teamSlug: string;
  championshipPosition: number;
  points: number;
  wins: number;
  podiums: number;
  poles: number;
  careerStarts: number;
  championships: number;
  positionChange: number;
  image?: string;
  imageAlt?: string;
  bio: string;
  seasonPoints: number[];
  raceResults: {
    race: string;
    qualifying: number;
    grid: number;
    finish: number | "DNF";
    points: number;
  }[];
}

export const drivers: Driver[] = [
  {
    slug: "max-verstappen",
    number: 1,
    firstName: "Max",
    lastName: "Verstappen",
    nationality: "Dutch",
    countryCode: "NL",
    dateOfBirth: "1997-09-30",
    team: "Oracle Red Bull Racing",
    teamSlug: "red-bull",
    championshipPosition: 1,
    points: 366,
    wins: 8,
    podiums: 13,
    poles: 6,
    careerStarts: 214,
    championships: 4,
    positionChange: 0,
    image: "/images/verstappen-red.jpg",
    imageAlt: "Max Verstappen in Oracle Red Bull Racing overalls holding his helmet",
    bio: "Four-time world champion, Verstappen remains the benchmark for one-lap pace and race management under pressure. Ruthless on cold tyres, immovable in a fight.",
    seasonPoints: [25, 43, 61, 85, 110, 134, 152, 181, 205, 229, 254, 278, 296, 318, 341, 366],
    raceResults: [
      { race: "Bahrain GP", qualifying: 1, grid: 1, finish: 1, points: 25 },
      { race: "Saudi Arabian GP", qualifying: 2, grid: 2, finish: 1, points: 25 },
      { race: "Australian GP", qualifying: 1, grid: 1, finish: 2, points: 18 },
      { race: "Japanese GP", qualifying: 1, grid: 1, finish: 1, points: 25 },
      { race: "Chinese GP", qualifying: 3, grid: 3, finish: "DNF", points: 0 },
      { race: "Miami GP", qualifying: 2, grid: 2, finish: 1, points: 25 },
    ],
  },
  {
    slug: "charles-leclerc",
    number: 16,
    firstName: "Charles",
    lastName: "Leclerc",
    nationality: "Monégasque",
    countryCode: "MC",
    dateOfBirth: "1997-10-16",
    team: "Scuderia Ferrari",
    teamSlug: "ferrari",
    championshipPosition: 2,
    points: 298,
    wins: 4,
    podiums: 11,
    poles: 5,
    careerStarts: 148,
    championships: 0,
    positionChange: 1,
    image: "/images/leclerc-portrait.jpg",
    imageAlt: "Charles Leclerc in Scuderia Ferrari race suit resting on his helmet",
    bio: "Leclerc pairs raw qualifying speed with a growing tactical maturity, dragging Ferrari's package into contention weekend after weekend at Maranello's home team.",
    seasonPoints: [18, 33, 52, 70, 89, 112, 130, 151, 172, 190, 214, 236, 255, 276, 298],
    raceResults: [
      { race: "Bahrain GP", qualifying: 2, grid: 2, finish: 3, points: 18 },
      { race: "Saudi Arabian GP", qualifying: 3, grid: 3, finish: 2, points: 18 },
      { race: "Australian GP", qualifying: 2, grid: 2, finish: 1, points: 25 },
      { race: "Japanese GP", qualifying: 4, grid: 4, finish: 3, points: 16 },
      { race: "Chinese GP", qualifying: 1, grid: 1, finish: 1, points: 25 },
      { race: "Miami GP", qualifying: 5, grid: 5, finish: 4, points: 13 },
    ],
  },
  {
    slug: "lewis-hamilton",
    number: 44,
    firstName: "Lewis",
    lastName: "Hamilton",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1985-01-07",
    team: "Scuderia Ferrari",
    teamSlug: "ferrari",
    championshipPosition: 4,
    points: 241,
    wins: 2,
    podiums: 8,
    poles: 2,
    careerStarts: 356,
    championships: 7,
    positionChange: -1,
    image: "/images/hamilton-portrait.jpg",
    imageAlt: "Lewis Hamilton in Scuderia Ferrari red race suit leaning on his yellow-visored helmet",
    bio: "The most decorated driver on the grid, Hamilton brought two decades of race-craft to Maranello and is still finding the edges of a new car and a new team culture.",
    seasonPoints: [15, 27, 40, 58, 74, 91, 105, 124, 142, 159, 178, 196, 214, 228, 241],
    raceResults: [
      { race: "Bahrain GP", qualifying: 5, grid: 5, finish: 5, points: 10 },
      { race: "Saudi Arabian GP", qualifying: 4, grid: 4, finish: 4, points: 12 },
      { race: "Australian GP", qualifying: 3, grid: 3, finish: 5, points: 10 },
      { race: "Japanese GP", qualifying: 6, grid: 6, finish: 6, points: 8 },
      { race: "Chinese GP", qualifying: 4, grid: 4, finish: 2, points: 18 },
      { race: "Miami GP", qualifying: 3, grid: 3, finish: 1, points: 25 },
    ],
  },
  {
    slug: "lando-norris",
    number: 4,
    firstName: "Lando",
    lastName: "Norris",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1999-11-13",
    team: "McLaren F1 Team",
    teamSlug: "mclaren",
    championshipPosition: 3,
    points: 279,
    wins: 3,
    podiums: 10,
    poles: 4,
    careerStarts: 132,
    championships: 0,
    positionChange: 0,
    bio: "Norris has turned McLaren's resurgence into genuine title pace, combining smooth inputs with a sharpened race start that finally matches his qualifying speed.",
    image: "/images/norris-portrait.jpg",
    imageAlt: "Lando Norris in McLaren papaya race suit against an orange graphic backdrop",
    seasonPoints: [12, 30, 48, 66, 88, 106, 128, 148, 166, 190, 208, 228, 248, 264, 279],
    raceResults: [
      { race: "Bahrain GP", qualifying: 4, grid: 4, finish: 4, points: 12 },
      { race: "Saudi Arabian GP", qualifying: 1, grid: 1, finish: 3, points: 15 },
      { race: "Australian GP", qualifying: 4, grid: 4, finish: 3, points: 15 },
      { race: "Japanese GP", qualifying: 2, grid: 2, finish: 2, points: 18 },
      { race: "Chinese GP", qualifying: 5, grid: 5, finish: 4, points: 12 },
      { race: "Miami GP", qualifying: 1, grid: 1, finish: 2, points: 18 },
    ],
  },
  {
    slug: "george-russell",
    number: 63,
    firstName: "George",
    lastName: "Russell",
    nationality: "British",
    countryCode: "GB",
    dateOfBirth: "1998-02-15",
    team: "Mercedes-AMG Petronas",
    teamSlug: "mercedes",
    championshipPosition: 5,
    points: 213,
    wins: 1,
    podiums: 6,
    poles: 2,
    careerStarts: 130,
    championships: 0,
    positionChange: 2,
    bio: "The de facto leader of the Silver Arrows rebuild, Russell brings clinical strategy calls and consistent points-scoring to a team still chasing its next title-winning car.",
    image: "/images/russell-portrait.jpg",
    imageAlt: "George Russell in Mercedes-AMG Petronas race suit against a teal graphic backdrop",
    seasonPoints: [10, 20, 38, 52, 70, 84, 100, 118, 134, 150, 168, 184, 198, 213],
    raceResults: [
      { race: "Bahrain GP", qualifying: 6, grid: 6, finish: 6, points: 8 },
      { race: "Saudi Arabian GP", qualifying: 5, grid: 5, finish: 5, points: 10 },
      { race: "Australian GP", qualifying: 5, grid: 5, finish: 4, points: 12 },
      { race: "Japanese GP", qualifying: 3, grid: 3, finish: 4, points: 12 },
      { race: "Chinese GP", qualifying: 6, grid: 6, finish: 5, points: 10 },
      { race: "Miami GP", qualifying: 4, grid: 4, finish: 3, points: 15 },
    ],
  },
  {
    slug: "sergio-perez",
    number: 11,
    firstName: "Sergio",
    lastName: "Pérez",
    nationality: "Mexican",
    countryCode: "MX",
    dateOfBirth: "1990-01-26",
    team: "Oracle Red Bull Racing",
    teamSlug: "red-bull",
    championshipPosition: 6,
    points: 187,
    wins: 0,
    podiums: 4,
    poles: 0,
    careerStarts: 288,
    championships: 0,
    positionChange: -1,
    bio: "Pérez remains Red Bull's tyre-management specialist, tasked with turning steady points into a Constructors' cushion while Verstappen fights up front.",
    image: "/images/perez-portrait.jpg",
    imageAlt: "Sergio Pérez in Oracle Red Bull Racing suit holding his helmet",
    seasonPoints: [8, 16, 28, 42, 58, 70, 86, 100, 114, 128, 144, 160, 174, 187],
    raceResults: [
      { race: "Bahrain GP", qualifying: 8, grid: 8, finish: 7, points: 6 },
      { race: "Saudi Arabian GP", qualifying: 7, grid: 7, finish: 6, points: 8 },
      { race: "Australian GP", qualifying: 8, grid: 8, finish: 8, points: 4 },
      { race: "Japanese GP", qualifying: 7, grid: 7, finish: 5, points: 10 },
      { race: "Chinese GP", qualifying: 9, grid: 9, finish: 7, points: 6 },
      { race: "Miami GP", qualifying: 6, grid: 6, finish: 5, points: 10 },
    ],
  },
  {
    slug: "fernando-alonso",
    number: 14,
    firstName: "Fernando",
    lastName: "Alonso",
    nationality: "Spanish",
    countryCode: "ES",
    dateOfBirth: "1981-07-29",
    team: "Aston Martin Aramco F1 Team",
    teamSlug: "aston-martin",
    championshipPosition: 7,
    points: 96,
    wins: 0,
    podiums: 2,
    poles: 0,
    careerStarts: 412,
    championships: 2,
    positionChange: 1,
    image: "/images/alonso-portrait.jpg",
    imageAlt: "Fernando Alonso in Aston Martin Aramco race suit against a dark backdrop",
    bio: "The grid's most experienced campaigner shows no sign of slowing down, still extracting results a car has no right to deliver through sheer race-craft and patience.",
    seasonPoints: [6, 12, 22, 34, 44, 54, 62, 70, 78, 84, 88, 92, 94, 96],
    raceResults: [
      { race: "Bahrain GP", qualifying: 9, grid: 9, finish: 8, points: 4 },
      { race: "Saudi Arabian GP", qualifying: 10, grid: 10, finish: 9, points: 2 },
      { race: "Australian GP", qualifying: 8, grid: 8, finish: 7, points: 6 },
      { race: "Japanese GP", qualifying: 9, grid: 9, finish: 3, points: 15 },
      { race: "Chinese GP", qualifying: 11, grid: 11, finish: 10, points: 1 },
      { race: "Miami GP", qualifying: 7, grid: 7, finish: 3, points: 15 },
    ],
  },
  {
    slug: "lance-stroll",
    number: 18,
    firstName: "Lance",
    lastName: "Stroll",
    nationality: "Canadian",
    countryCode: "CA",
    dateOfBirth: "1998-10-29",
    team: "Aston Martin Aramco F1 Team",
    teamSlug: "aston-martin",
    championshipPosition: 12,
    points: 41,
    wins: 0,
    podiums: 0,
    poles: 0,
    careerStarts: 168,
    championships: 0,
    positionChange: -1,
    image: "/images/stroll-portrait.jpg",
    imageAlt: "Lance Stroll in Aston Martin Aramco race suit standing in the garage",
    bio: "Stroll continues to develop alongside the team his family helped build, focused on consistent points-scoring while Aston Martin refines its championship ambitions.",
    seasonPoints: [2, 4, 8, 14, 18, 22, 26, 30, 33, 36, 38, 39, 40, 41],
    raceResults: [
      { race: "Bahrain GP", qualifying: 13, grid: 13, finish: 11, points: 0 },
      { race: "Saudi Arabian GP", qualifying: 12, grid: 12, finish: 10, points: 1 },
      { race: "Australian GP", qualifying: 14, grid: 14, finish: 9, points: 2 },
      { race: "Japanese GP", qualifying: 11, grid: 11, finish: 8, points: 4 },
      { race: "Chinese GP", qualifying: 13, grid: 13, finish: 12, points: 0 },
      { race: "Miami GP", qualifying: 10, grid: 10, finish: 8, points: 4 },
    ],
  },
  {
    slug: "pierre-gasly",
    number: 10,
    firstName: "Pierre",
    lastName: "Gasly",
    nationality: "French",
    countryCode: "FR",
    dateOfBirth: "1996-02-07",
    team: "BWT Alpine F1 Team",
    teamSlug: "alpine",
    championshipPosition: 8,
    points: 68,
    wins: 0,
    podiums: 1,
    poles: 0,
    careerStarts: 172,
    championships: 0,
    positionChange: 0,
    image: "/images/gasly-portrait.jpg",
    imageAlt: "Pierre Gasly in BWT Alpine race suit resting his arm on his hip",
    bio: "Alpine's team leader on and off the track, Gasly has kept Enstone competitive through a difficult regulation cycle with a string of gritty midfield drives.",
    seasonPoints: [4, 10, 18, 26, 34, 40, 46, 52, 57, 61, 64, 66, 67, 68],
    raceResults: [
      { race: "Bahrain GP", qualifying: 10, grid: 10, finish: 9, points: 2 },
      { race: "Saudi Arabian GP", qualifying: 9, grid: 9, finish: 8, points: 4 },
      { race: "Australian GP", qualifying: 11, grid: 11, finish: 6, points: 8 },
      { race: "Japanese GP", qualifying: 10, grid: 10, finish: 9, points: 2 },
      { race: "Chinese GP", qualifying: 8, grid: 8, finish: 5, points: 10 },
      { race: "Miami GP", qualifying: 12, grid: 12, finish: 9, points: 2 },
    ],
  },
  {
    slug: "jack-doohan",
    number: 61,
    firstName: "Jack",
    lastName: "Doohan",
    nationality: "Australian",
    countryCode: "AU",
    dateOfBirth: "2003-01-20",
    team: "BWT Alpine F1 Team",
    teamSlug: "alpine",
    championshipPosition: 15,
    points: 12,
    wins: 0,
    podiums: 0,
    poles: 0,
    careerStarts: 22,
    championships: 0,
    positionChange: 0,
    image: "/images/alpine-driver-portrait.jpg",
    imageAlt: "Alpine driver in BWT race suit against a smoky studio backdrop",
    bio: "A rookie season under pressure, Doohan is learning the sport's toughest lessons in real time as Alpine builds its next generation of racing talent around him.",
    seasonPoints: [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 10, 11, 11, 12],
    raceResults: [
      { race: "Bahrain GP", qualifying: 16, grid: 16, finish: 14, points: 0 },
      { race: "Saudi Arabian GP", qualifying: 15, grid: 15, finish: 12, points: 0 },
      { race: "Australian GP", qualifying: 17, grid: 17, finish: 13, points: 0 },
      { race: "Japanese GP", qualifying: 14, grid: 14, finish: 10, points: 1 },
      { race: "Chinese GP", qualifying: 16, grid: 16, finish: 11, points: 0 },
      { race: "Miami GP", qualifying: 13, grid: 13, finish: 9, points: 2 },
    ],
  },
];

export function getDriverBySlug(slug: string) {
  return drivers.find((d) => d.slug === slug);
}
